apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T07:01:09Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "644"
  uid: 552d50f0-375c-46de-b4df-e62636faeae1
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.107.227.2
  clusterIPs:
  - 10.107.227.2
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32388
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
