apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-13T06:46:59Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1386"
  uid: 705126e0-53e3-40ba-8660-3e2a4a22dee7
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.108.31.192
  clusterIPs:
  - 10.108.31.192
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31014
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
